AMREX_HOME ?= ../../../../amrex/
USE_EB = TRUE
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

#USE_PARTICLES = TRUE

USE_MPI    = FALSE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include Make.Adv
